# Generated by Django 5.2.8 on 2025-11-17 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entrada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='texto',
            new_name='text',
        ),
    ]
